.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PAI-SUMMARY-BY-LEVEL 6 "May 18, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pai-summary-by-level \- minimal launcher for PAI summary (by level)
.SH SYNOPSIS
.B pai-summary-by-level
.SH DESCRIPTION
This manual page summary-by-leveluments briefly the
.B pai-summary-by-level
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBpai-summary-by-level\fP is a minimal script used to launch PAI summary (by level).
.SH OPTIONS
These minimal launcher has no options.
.TP
.SH SEE ALSO
.BR pai (6),
.BR pai-changelog (6),
.BR pai-doc (6),
.BR pai-summary-by-discipline (6).
.SH AUTHOR
.B pai-summary-by-level
was written by Laércio de Sousa. PAI was written by
Orientadores de Informática.
.PP
This manual page was written by Laércio de Sousa <lbsousajr@gmail.com>,
for the Debian project (and may be used by others).
