usr/share/applications/pmmc-pte-pai-doc.desktop usr/share/applications
usr/share/applications/pmmc-pte-pai-changelog.desktop usr/share/applications
usr/share/applications/pmmc-pte-pai-summary-by-discipline.desktop usr/share/applications
usr/share/applications/pmmc-pte-pai-summary-by-level.desktop usr/share/applications
usr/games/pai-doc usr/games
usr/games/pai-changelog usr/games
usr/games/pai-summary-by-discipline usr/games
usr/games/pai-summary-by-level usr/games
